cul/ldpd-dcv

- app/controllers/concerns/dcv/catalog/browse_list_behavior.rb
- app/controllers/home_controller.rb
- app/controllers/welcome_controller.rb
- Facet browse cache key is now dependent on enclosing controller
> Fixes DCV-404

- app/helpers/ifp/partner_data_helper.rb
- app/views/ifp/home.html.erb
- app/views/ifp/partner/_office_sidebar.html.erb
pls to check to ensure the new changes to finding_aid :id won't mess anything up
> IFP-44 finding aid link updates

- app/controllers/sites_controller.rb
- app/views/pages/projects_and_exhibitions.html.erb
- app/views/shared/_head_includes.html.erb
- app/views/shared/_topnavbar.html.erb
> Validation updates

- app/views/lcaaj/home.html.erb
> DCV-521 - LCAAJ Add grant info to Homepage

- app/assets/javascripts/dcv/dcv.general.js
turned on fancy tooltips for all subsites. removed junk.
> fancy_tooltips

- app/assets/stylesheets/dcv/dcv.css.scss
- app/helpers/catalog_helper.rb
- app/helpers/dcv/iframe_helper_behavior.rb
- app/views/catalog/content_aggregator/_content_aggregator_viewer.html.erb
- spec/helpers/catalog_helper_spec.rb
if url location is at archive.org
> embed archive.org iframe

- app/assets/stylesheets/carnegie/carnegie.scss
- app/views/carnegie/_grid.html.erb
- app/views/catalog/_document_list.html.erb
Wrap titles in grid view of search results display
> Closes CARNEGIE-121. multiline truncation with ellipsis, partial, etc

- app/views/carnegie/_secondary_nav.html.erb
> added Archived Corporation Websites to Related Resources dropdown. 

- app/views/ifp/home.html.erb
- app/views/ifp/partner/_office_sidebar.html.erb
removes traces of "IFP Legacy Website". remove "IFP Community" block on partner pages sidebar
> Closes IFP-89. IFP: Remove "partner" content section from IFP country home pages

- app/assets/stylesheets/_base_layout.scss
- app/assets/stylesheets/portrait/_base.scss
- app/views/layouts/portrait.html.erb
- app/views/shared/content_aggregator/_button_panel.html.erb
> Dlc 774 portrait layout phase ii

- app/assets/javascripts/dcv/dcv.general.js
- app/assets/stylesheets/_base_layout.scss
- app/views/sites/_secondary_nav.html.erb
> permanent URL ui in secondary nav is a button to copy to clipboard (DLC-798)

- app/assets/stylesheets/gallery/_base.scss
> Dlc 775 gallery layout phase ii

- app/views/layouts/details.html.erb
- app/views/layouts/gallery.html.erb
- app/views/layouts/minimal.html.erb
- app/views/layouts/portrait.html.erb
- app/views/layouts/signature.html.erb
- app/views/layouts/sites.html.erb
- footer is sibling to main-container
- main-container consistently classed container
- empty partial renders removed
- indentation consistency site layout templates
> harmonize main-container class and footer placement across site layouts

- README.md
- app/controllers/users/omniauth_callbacks_controller.rb
- lib/tasks/ci.rake
- lib/tasks/dcv/users.rake
- add local suer account management rake tasks
- update cas config initializer to set fields per local use
- fix developer strategy
> document local development startup in README (DLC-870)

- app/controllers/concerns/dcv/catalog/cached_fetch_behavior.rb
- app/controllers/iiif/presentations_controller.rb
- app/models/iiif/manifest.rb
> IIIF::PresentationsController uses BL7 fetch behaviors

- app/helpers/dcv/media_element_helper.rb
- app/javascript/stylesheets/_base_layout.scss
- app/views/shared/content_aggregator/_button_panel.html.erb
> inline iiif logo svg and style for primary and secondary ui options

- app/helpers/dcv/blacklight_helper_behavior.rb
- app/views/shared/_head_includes.html.erb
- app/views/shared/content_aggregator/_button_panel.html.erb
- app/views/shared/content_aggregator/carousel/_archive_org.html.erb
- app/views/shared/content_aggregator/carousel/_structured_children.html.erb
> Dlc 951 accessibility

- app/javascript/src/dcv/dcv.modals.js
- app/javascript/src/dcv/downloadsButton.js
- app/views/layouts/gallery.html.erb
- app/views/layouts/minimal.html.erb
- app/views/layouts/portrait.html.erb
- app/views/layouts/signature.html.erb
- app/views/layouts/sites.html.erb
- app/views/shared/_previous_next_doc.html.erb
- app/views/shared/_show_tools_collection.html.erb
- app/views/shared/_show_tools_content_aggregator.html.erb
- app/views/shared/_topnavbar.html.erb
- app/views/shared/content_aggregator/child_viewer/_button_panel.html.erb
DLC-997 Download menu clipping resolved by moving to modal
DLC-998 topnav is no longer fixed, to prevent unexpected layout changes from modal functions
DLC-999 show view layout improvements for mobile to prevent long titles from obscuring UI
DLC-1000 add menuitem role to citation menu options
> Fix layout and accessibility issues with show view UI

- app/controllers/concerns/dcv/sites/lookup_controller.rb
- app/controllers/resolve/catalog_controller.rb
- app/controllers/resolve/dois_controller.rb
- spec/controllers/concerns/dcv/sites/lookup_controller_spec.rb
- spec/controllers/resolve/catalog_controller_spec.rb
- spec/routing/resolve/catalog_controller_spec.rb
- extract best-site scoring into LookupController concern and spec
- spec routes for resolve/catalog
- spec resolving controller
- DLC-1044
> The resolve/catalog controller should use site-scoring logic to build redirect

- app/components/dcv/document_component.html.erb
- app/components/dcv/document_component.rb
- app/controllers/iiif/presentations_controller.rb
- app/controllers/sites/search_configuration_controller.rb
- app/helpers/dcv/field_sets_helper_behavior.rb
- app/helpers/field_display_helpers/name.rb
- app/helpers/field_display_helpers/project.rb
- app/helpers/field_display_helpers/repository.rb
- app/models/site.rb
- app/models/site/display_options.rb
- app/presenters/dcv/field_presenter.rb
- app/presenters/dcv/rendering/link_to_facet.rb
- app/views/sites/search_configuration/_display_options_form.html.erb
- lib/dcv/configurators/carnegie_blacklight_configurator.rb
- lib/dcv/configurators/dcv_blacklight_configurator.rb
- lib/dcv/configurators/durst_blacklight_configurator.rb
- lib/dcv/configurators/ifp_blacklight_configurator.rb
- lib/dcv/configurators/jay_blacklight_configurator.rb
- lib/dcv/configurators/lcaaj_blacklight_configurator.rb
- lib/dcv/configurators/nyre_blacklight_configurator.rb
- lib/dcv/configurators/restricted/universityseminars_blacklight_configurator.rb
- spec/components/dcv/document_component_spec.rb
- spec/features/sites/search_configuration_controller_spec.rb
- spec/fixtures/sites/import/directory/properties.yml
- spec/helpers/field_display_helpers/project_spec.rb
- spec/presenters/dcv/field_presenter_spec.rb
* There should be a rudimentary search result configuration for tombstone fields
* relatedItem[@otherType] should be included in show fields
> DLC-1143 and DLC-1144

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
Ran into some deployment issues so I fixed them and standardized our deployment setup to align with other apps (and use our capistrano-cul gem).
> Deployment fixes/updates

- .github/workflows/ci.yml
- Gemfile
- app/javascript/iiif.js
- package.json
- yarn.lock
Plus some minor file reformatting/cleanup.
> Update cul mirador
